spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    name: postgres
    password: postgres
    username: postgres
server:
  port: 8085

#docker run --name postgres -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 postgres